extends: ['./.eslintrc.yml', './node_modules/@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended.js']
parser: '@typescript-eslint/parser'
rules:
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
